[network]
model = 'res_3D2D_hybrid_net_multi_output'

#trained_file = 'model/Mdecoder2Unet_withDilatConv_in_3_chs_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_freeze_net1=True_iter_32499.model'
#trained_file = 'model/Mdecoder2Unet_in_3_chs__[affinity-sizemap-distance-gradient_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_freeze_net1=True_iter_325749.model'
#trained_file = 'model/Mdecoder2Unet_in_3_chs__[affinity-sizemap-distance-gradient_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_freeze_net1=True_iter_4399.model'
#train_file = 'model/Mdecoder2Unet_in_3_chs__[affinity-sizemap-distance-gradient_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_freeze_net1=True_iter_24199.model'

#trained_file ='model/Res_3D_2D_HybribUnet_multiHead_selfGated_act_Dataset-CRIME-All_affinityX-affinityY-affinityZ_VFlip-HFlip-Rot90-NRot90_patch =[256, 256, 22]_iter_103799.model'
trained_file ='model/Res_3D_2D_HybribUnet_multiHead_selfGated_act_Dataset-CRIME-All_affinityX-affinityY-affinityZ-distance2D-distance3D_VFlip-HFlip-Rot90-NRot90_patch =[256, 256, 22]_iter_176199.model'
use_gpu = true

[predict_setting]
preidct_patch_size =[1248,1248,25]
predict_overlap    =[1246,1246, 8]

[target_labels]
  # labels = ['affinityX',
  #           'affinityY',
  #           'affinityZ']
  labels = ['affinityX',
            'affinityY',
            'affinityZ',
            'distance2D',
            'distance3D']
  final_label = 'distance'

[dataset]
sub_dataset = 'All'
output_3D = true
dataset    = 'valid'

[data_augmentation]
 transform =['vflip',
            'hflip',
            'rot90',
            'nrot90']