[network]
#model = 'M2DUnet_withDilatConv'
#model ='MDUnet_FullDilat'
z_slices = 3

#trained_file = 'model/Mdecoder2Unet_withDilatConv_in_3_chs_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_freeze_net1=True_iter_32499.model'
#trained_file = 'model/Mdecoder2Unet_in_3_chs__[affinity-sizemap-distance-gradient_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_freeze_net1=True_iter_325749.model'
#trained_file = 'model_back/Mdecoder2Unet_in_3_chs__[affinity-sizemap-distance-gradient_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_freeze_net1=True_iter_4399.model'
#train_file = 'model/Mdecoder2Unet_in_3_chs__[affinity-sizemap-distance-gradient_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_freeze_net1=True_iter_24199.model'
#trained_file ='model/MdecoderUnetFullDilatConv_in_3_chs_Dataset-CRIME-All_affinity-centermap-distance-skeleton-gradient_VFlip-HFlip-Rot90_patch =[320, 320, 3]_iter_299.model'
#trained_file='model/MdecoderUnetFullDilatConv_in_3_chs_Dataset-CRIME-All_affinity-centermap-distance-skeleton-gradient_VFlip-HFlip-Rot90-NRot90_patch =[320, 320, 3]_iter_7499.model'
#trained_file ='model_back/Mdecoder2Unet_in_3_chs__[affinity-sizemap-distance-gradient_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_freeze_net1=True_iter_43999.model'

#use_gpu = true


#model = 'M2DUnet_withDilatConv'
model = 'MDUnet_FullDilat'
slices = 3
#trained_file ='model/Mdecoder2Unet_in_3_chs__[affinity-sizemap-distance-gradient_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_patch =[320, 320, 3]_freeze_net1=True_iter_206249.model'
#trained_file='model/Mdecoder2Unet_in_3_chs__[affinity-sizemap-distance-gradient_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_patch =[320, 320, 3]_freeze_net1=True_iter_318499.model'

trained_file='model/MdecoderUnetFullDilatConv_in_3_chs_Dataset-CRIME-All_affinity-centermap-distance-skeleton-gradient_VFlip-HFlip-Rot90-NRot90_patch =[480, 480, 3]_iter_13199.model'
use_gpu = true
[target_labels]
  labels = ['affinity',
            'centermap',
            'distance',
            'skeleton',
            'gradient']
  final_label = 'distance'
  # labels = ['affinity',
  #           'centermap',
  #           'distance',
  #           'skeleton',
  #           'gradient']
  label_catin_net2 = ['affinity',
            'centermap',
            'distance',
            'skeleton',
            'gradient']
  # label_catin_net2 =['affinity',
		#              'sizemap',
  #                    'distance',
  #                    'gradient']
  #final_label = 'distance'
[dataset]
dataset     = 'valid'
sub_dataset = 'All'
output_3D = true


[predict_setting]
preidct_patch_size =[1248,1248,25]
predict_overlap    =[1246,1246, 8]


[slice_direction]
direction ='low_res'
#option 'low_res','high_res'

#[dataset]
#dataset     = 'valid'
#option 'valid, predict' 
#sub_dataset = 'All'