[network]
model = 'MDUnet_FullDilat'
model_save_dir = 'model'
load_train_iter = 0
#trained_file  = 'model/MdecoderUnetDilatConv_in_3_chs_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_iter_155049.model'
#trained_file = 'model/MdecoderUnetDilatConv_in_3_chs_Dataset-CRIME-All_affinity-centermap-distance-gradient_VFlip-HFlip-Rot90_patch =[320, 320, 3]_iter_83699.model'
#trained_file ='model/MdecoderUnetDilatConv_in_3_chs_Dataset-CRIME-All_affinity-centermap-distance-skeleton-gradient_VFlip-HFlip-Rot90_patch =[320, 320, 3]_iter_11099.model'
#trained_file  ='model/MdecoderUnetDilatConv_in_3_chs_Dataset-CRIME-All_affinity-centermap-distance-skeleton-gradient_VFlip-HFlip-Rot90_patch =[320, 320, 3]_iter_56399.model'
model_save_step = 300
batch_size      = 5
patch_size      = [320,320,3]
use_gpu         = true


[train]
final_loss_only = false
learning_rate   = 0.01
tensorboard_folder = 'runs_train2D/Fulldialet_mnet_3ch_320_320_grad_and_weighted_tchick_skeleton'
optimizer = 'Adagrad'
#option{'SGD','Adagrad','Adam'}

#[sub_net]
#model = 'MDUnet'
#freeze_weight = false
#trained_file  = 'model/MdecoderUnet_Dataset-CRIME-All__iter_29999.model'


[target_labels]
  labels = ['affinity',
            'centermap',
            'distance',
            'skeleton',
            'gradient']
  final_label = 'distance'
[dataset]
sub_dataset = 'All'
# Options: {'Set_A','Set_B','Set_C','All'}

[data_augmentation]
 transform =['vflip',
            'hflip',
            'rot90']