[network]
model = 'MDUnetDilatCenterGate'
model_save_dir = 'model'
load_train_iter = 0
#trained_file  = 'model/MdecoderUnetDilatConvCenterGate_in_3_chs_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_patch =[320, 320, 3]_iter_5399.model'
model_save_step = 500
batch_size      = 3
patch_size      = [320,320,3]
use_gpu         = true
cgate_compress  = true


[train]
final_loss_only = false
learning_rate   = 0.01
tensorboard_folder = 'runs_train2D/dialet_mnet_3ch_centerGate_resume_non_batchnorm_compressed'
optimizer = 'Adam'
#option{'SGD','Adagrad','Adam'}

#[sub_net]
#model = 'MDUnet'
#freeze_weight = false
#trained_file  = 'model/MdecoderUnet_Dataset-CRIME-All__iter_29999.model'


[target_labels]
  labels = ['affinity',
            'centermap',
            'distance',
            'gradient']
  final_label = 'distance'
[dataset]
sub_dataset = 'All'
# Options: {'Set_A','Set_B','Set_C','All'}

[data_augmentation]
 transform =['vflip',
            'hflip',
            'rot90']