[network]
model = 'MDUnet'
model_save_dir = 'model'
load_train_iter = 0
model_save_step = 100
batch_size      = 3
patch_size = [320,320,1]
use_gpu    = true
[target_labels]
  labels = ['affinity',
           'sizemap',
           'centermap',
           'distance',
           'gradient']
[dataset]
sub_dataset = 'All'

[data_augmentation]
 transform =['vflip',
            'hflip',
            'rot90']