[mask_loader]
# options {'GT' , 'NN'}. 'GT' mask create based on ground truth, 'NN' based on segmentation created by 2D CNN
mode = 'NN'

# which network model to use to generate segmentation/ mask
nn_model = 'Mdecoder2Unet_withDilatConv'
nn_weight_file = 'model/Mdecoder2Unet_withDilatConv_in_3_chs_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_freeze_net1=True_iter_32499.model'
use_gpu    = true
labels_cat_in = ['affinity',
            'sizemap',
            'centermap',
            'gradient',
            'final']

[network]
model = 'MaskMDnetDialat'
#model ='GCN'
model_save_dir = 'model'
load_train_iter = 0
#trained_file  = 'model/NN_MdecoderUnetDilatConv_in_11_chs_Dataset-CRIME-All_mask_VFlip-HFlip-Rot90_iter_2479.model'
#trained_file ='model/NN_MdecoderUnetDilatConv_in_11_chs_Dataset-CRIME-All_mask_bce_loss_VFlip-HFlip-Rot90_iter_4399.model'
model_save_step = 200
batch_size      = 5
patch_size      = [320,320,3]
use_gpu         = true
valid_iters     = 150
#MaskMDnetDialat

[train]
learning_rate   = 0.01
tensorboard_folder = 'runs/mask_DialetUnet_3ch_320x320_MASK_BCELoss_first_ch=32'
loss_fn = 'mask_bce'
#option {bce, dice, mse,bce_logit,mask_bce}
optimizer = 'Adagrad'
#option{'SGD','Adagrad'}

[dataset]
sub_dataset = 'All'
# Options: {'Set_A','Set_B','Set_C','All'}

[data_augmentation]
 transform =['vflip',
            'hflip',
            'rot90']