[network]
model = 'M2DUnet_withDilatConv'
model_save_dir = 'model'
load_train_iter = 0
#trained_file  = 'model/Mdecoder2Unet_withDilatConv_in_3_chs_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_freeze_net1=True_iter_11749.model'
trained_file ='model/Mdecoder2Unet_in_3_chs__[affinity-sizemap-distance-gradient_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_freeze_net1=True_iter_327249.model'
model_save_step = 200
batch_size      = 6
patch_size      = [3,640,96]
use_gpu         = true

[train]
loss_fn = 'mse'
#option {bce, dice, mse, bce_logit, mask_bce}
# only works for masknet
optimizer = 'Adam'
#option{'SGD','Adagrad','Adam'}
final_loss_only = true
learning_rate   = 0.01
tensorboard_folder = 'runs_train2D/mDecoder2Unet_Dilat_3ch_480x480_lesscat_labels'

[sub_net]
model = 'MDUnetDilat'
freeze_weight = true
#trained_file  = 'model/MdecoderUnetDilatConv_in_3_chs_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_iter_155049.model'


[target_labels]
  labels = ['affinity',
            'sizemap',
            'centermap',
            'distance',
            'gradient']
label_catin_net2 =['affinity',
					'sizemap',
				   'distance',
				   'gradient']
final_label = 'distance'
[dataset]
sub_dataset = 'All'
# Options: {'Set_A','Set_B','Set_C','All'}

[data_augmentation]
 transform =['vflip',
            'hflip',
            'rot90']