[network]
model = 'MDUnetDilat'
model_save_dir = 'model'
load_train_iter = 0
#trained_file  = 'model/MdecoderUnetDilatConv_in_3_chs_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient__iter_1749.model'
model_save_step = 350
batch_size      = 6
patch_size      = [320,320,5]
use_gpu         = true


[train]
final_loss_only = true
learning_rate   = 0.01

#[sub_net]
#model = 'MDUnet'
#freeze_weight = false
#trained_file  = 'model/MdecoderUnet_Dataset-CRIME-All__iter_29999.model'


[target_labels]
  labels = ['affinity',
            'sizemap',
            'centermap',
            'distance',
            'gradient']
  final_label = 'distance'
[dataset]
sub_dataset = 'All'
# Options: {'Set_A','Set_B','Set_C','All'}

[data_augmentation]
 transform =['vflip',
            'hflip',
            'rot90']