[network]
model = 'MDUnetDilat'
model_save_dir = 'model'
load_train_iter = 0
#trained_file  = 'model/MdecoderUnetDilatConv_in_3_chs_Dataset-CRIME-All_affinity-sizemap-centermap-distance-gradient_VFlip-HFlip-Rot90_iter_155049.model'
model_save_step = 300
batch_size      = 8
patch_size      = [5,640,96]
use_gpu         = true


[train]
final_loss_only = false
learning_rate   = 0.01
tensorboard_folder = 'runs_train2D/dialet_mnet_5ch_480_480_sidePatch'
optimizer = 'Adam'
#option{'SGD','Adagrad','Adam'}

#[sub_net]
#model = 'MDUnet'
#freeze_weight = false
#trained_file  = 'model/MdecoderUnet_Dataset-CRIME-All__iter_29999.model'


[target_labels]
  labels = ['affinity',
            'sizemap',
            'centermap',
            'distance',
            'gradient']
  final_label = 'distance'
[dataset]
sub_dataset = 'All'
# Options: {'Set_A','Set_B','Set_C','All'}

[data_augmentation]
 transform =['vflip',
            'hflip']